- name: Load OS-specific vars
  ansible.builtin.include_vars: "vars/{{ ansible_os_family | lower }}.yml"

- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
